version: '3.7'

services:
  web:
    container_name: cartera-web
    image: nginx:mainline-alpine3.18-perl
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./config:/etc/nginx/conf.d
      - ./client/dist:/usr/share/nginx/html
    environment:
      - TZ=America/Bogota
    networks:
      - internal_cartera

  api:
    container_name: cartera-api
    build:
      context: .
      dockerfile: Dockerfile
    image: cartera-api:1.0
    restart: always
    environment:
      - TZ=America/Bogota
    networks:
      - internal_cartera

networks:
  internal_cartera:
    driver: bridge